# Generated by Django 3.0.3 on 2020-02-20 15:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200220_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='date',
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
